# fly.toml file generated for pipodashboard on 2023-02-28T07:58:28-05:00

app = "pipodashboard"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_USER = 'q0loyoerxyyxhqfhe2gu'
  DATABASE_PASSWORD = 'pscale_pw_dYX0PFurK1Gf1i8oS8f7Kyztjxv0ft5EfbNVfS6mgF7'
  DATABASE_NAME = 'dbpipo'
  DATABASE_HOST = 'aws.connect.psdb.cloud'

  TOKEN_SECRET = "pipotex1977"

  GET_CLIENTS_GENERAL = "SELECT cliente.idcliente, persona.nombre, persona.apellido, persona.razon_social AS nro_doc, persona.fecha_cumpleannos, persona.telefono,persona.direccion, cliente.saldo,cliente.email AS correo, cliente.credito_limite, cliente.esVip, persona.genero FROM persona, cliente WHERE persona.idpersona = cliente.persona_idpersona ORDER BY persona.nombre ASC;"
  GET_IDPERSONA = "SELECT persona_idpersona FROM cliente WHERE idcliente = ?"
  GET_REP_PERSONA = "SELECT COUNT(*) AS repeticiones FROM persona WHERE razon_social = ?;"
  GET_CIENT_BY_ID = "SELECT persona.razon_social AS documento, persona.nombre,persona.apellido, persona.fecha_cumpleannos, persona.telefono, persona.genero,cliente.ultimo_pago, cliente.saldo, cliente.credito_limite, cliente.email AS correo, cliente.estrellas, cliente.detalle FROM persona, cliente WHERE persona.idpersona = cliente.persona_idpersona AND cliente.idcliente = ?;"

  UPDATE_PERSON = "UPDATE persona SET nombre = ?, apellido = ?, telefono = ?, razon_social = ?, genero = ?, direccion = ? WHERE idpersona = (SELECT persona_idpersona FROM cliente WHERE idcliente = ?);"
  UPDATE_CLIENT = "UPDATE cliente SET  email = ? WHERE idcliente = ?;"
  UPDATE_NAME_PERSON = "UPDATE persona SET nombre = ? WHERE idpersona = (SELECT persona_idpersona FROM cliente WHERE idcliente = ?) ;"
  UPDATE_TEL_PERSON = "UPDATE persona SET telefono = ? WHERE idpersona = (SELECT persona_idpersona FROM cliente WHERE idcliente = ?) ;"
  UPDATE_LAST_NAME_PERSON = "UPDATE persona SET apellido = ? WHERE idpersona = (SELECT persona_idpersona FROM cliente WHERE idcliente = ?) ;"
  UPDATE_RAZON_SOCIAL = "UPDATE persona SET razon_social = ? WHERE idpersona = (SELECT persona_idpersona FROM cliente WHERE idcliente = ?) ;"
  UPDATE_EMAIL = "UPDATE cliente SET email = ? WHERE idcliente = ? ;"
  UPDATE_SALDO = "UPDATE cliente SET saldo = ? WHERE idcliente = ? ;"

  CREATE_PERSON = "INSERT INTO persona (nombre,apellido,fecha_cumpleannos,fecha_creacion,telefono,razon_social,genero,esAdmin,direccion) VALUES (?,?,?,?,?,?,?,?,?)"
  CREATE_CLIENT = "INSERT INTO cliente (idcliente,persona_idpersona,credito_limite,detalle,saldo,email,duracion_credit,esVip,estrellas) VALUES(?,?,?,?,?,?,?,?,?)"

  DELETE_PERSON = "DELETE FROM persona WHERE idpersona = ? "
  DELETE_CLIENT = "DELETE FROM cliente WHERE idcliente = ? "

  CLOUDINARY_NAME = "dru6kde3e"
  CLOUDINARY_API_SECRET = "RqejzEsCO3VGmbe0qhR_pc_Qg2Q"
  CLOUDINARY_API_KEY="939691988994216"
  CLOUDINARY_ENVIROMENT="CLOUDINARY_URL=cloudinary://939691988994216:RqejzEsCO3VGmbe0qhR_pc_Qg2Q@dru6kde3e"
[build.args]


[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
